language: python
# http://blog.travis-ci.com/2014-12-17-faster-builds-with-container-based-infrastructure/
sudo: false

env:
  - TOXENV=py26
  - TOXENV=py27
  - TOXENV=py33
  - TOXENV=pypy
  - TOXENV=py34

install:
  - pip install -q tox 

  # for python versions <27, we must install ordereddict
  # mimicking the same dynamically generated 'requires='
  # in setup.py
  - if [[ "${TOXENV}" == "py25" ]] || [[ "${TOXENV}" == "py26" ]]; then
        pip install -q ordereddict;
    fi

  # for python version =27, install coverage, coveralls.
  # (coverage only measured and published for one version)
  - if [[ "${TOXENV}" == "py34" ]]; then
        pip install -q coverage coveralls;
    fi

script:
  - if [[ "${TOXENV}" == "py27" ]]; then tox -e sa; fi
  - if [[ "${TOXENV}" == "py34" ]]; then tox -e docs; fi
  - tox -e $TOXENV

notifications:
  email:
    - contact@jeffquast.com
