language: python
matrix:
  fast_finish: true
  include:
    - python: 2.7
      env: TOXENV=py27 TEST_QUICK=1 COVERAGE_ID=travis-ci
    - python: 3.4
      env: TOXENV=py34 TEST_QUICK=1 COVERAGE_ID=travis-ci
    - python: 3.5
      env: TOXENV=py35 TEST_QUICK=1 COVERAGE_ID=travis-ci
    - python: 3.6
      env: TOXENV=py36 COVERAGE_ID=travis-ci
    - python: 3.7
      env: TOXENV=py37 COVERAGE_ID=travis-ci
    - python: 3.8
      env: TOXENV=py38 COVERAGE_ID=travis-ci
    - python: 3.9-dev
      env: TOXENV=py39 COVERAGE_ID=travis-ci
    - env: TOXENV=about
    - env: TOXENV=pylint
    - env: TOXENV=flake8
    - env: TOXENV=pycodestyle
    - env: TOXENV=sphinx
    - env: TOXENV=sa

jobs:
  allow_failures:
  - python: 3.9-dev

install:
  - pip install tox
script:
  - tox
sudo: false

notifications:
  email:
    recipients:
      - contact@jeffquast.com
    on_success: change
    on_failure: change
