language: python
sudo: false

before_script:
  - pip install -q tox
script:
  - tox

matrix:
  fast_finish: true
  include:
    - env: TOXENV=about
    - env: TOXENV=sa
    - env: TOXENV=sphinx
    - python: 2.7
      env: TOXENV=py27 TEST_QUICK=1
    - python: 3.4
      env: TOXENV=py34 TEST_QUICK=1
    - python: 3.5
      env: TOXENV=py35

notifications:
  email:
    recipients:
      - contact@jeffquast.com
    on_success: change
    on_failure: change
  irc:
    channels:
      - "irc.servercentral.net#1984"
    template:
      - "%{repository}(%{branch}): %{message} (%{duration}) %{build_url}"
    skip_join: true
    on_success: change
    on_failure: change
